export const infoTour = [
  {
    id: 1,
    imgTour: '../images/tour-1.jpeg',
    date: 'august 26th, 2020',
    tourtitle: 'Tibet Adventure',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumquevitae tempore voluptatum maxime reprehenderit eum quodexercitationem fugit, qui corporis.',
    country: 'china',
    days: '6 days',
    price: ' 2100',
  },
  {
    id: 2,
    imgTour: '../images/tour-2.jpeg',
    date: 'october 1th, 2020',
    tourtitle: 'best of java',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumquevitae tempore voluptatum maxime reprehenderit eum quodexercitationem fugit, qui corporis.',
    country: 'indonesia',
    days: '11 days',
    price: ' 1400',
  },
  {
    id: 3,
    imgTour: '../images/tour-3.jpeg',
    date: 'september 15th, 2020',
    tourtitle: 'explore hong kong',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumquevitae tempore voluptatum maxime reprehenderit eum quodexercitationem fugit, qui corporis.',
    country: ' hong kong',
    days: '8 days',
    price: ' 5000',
  },
  {
    id: 4,
    imgTour: '../images/tour-4.jpeg',
    date: 'december 5th, 2019',
    tourtitle: 'kenya highlights',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumquevitae tempore voluptatum maxime reprehenderit eum quodexercitationem fugit, qui corporis.',
    country: 'kenya',
    days: '20 days',
    price: ' 3300',
  },
]